---
- name: Install MySQL server
  hosts: db
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started

- name: Create MySQL database
  hosts: db
  become: yes

  vars:
    mysql_root_password: secret
    mysql_database: tooling
    mysql_user: webaccess
    mysql_password: mypass

  tasks:
    - name: Install MySQL client
      apt:
        name: mysql-client
        state: present

    - name: Create MySQL database
      mysql_db:
        name: "{{ mysql_database }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        priv: "{{ mysql_database }}.*:ALL"
        state: present


