
[nfs]
172.31.88.227 ansible_ssh_user='ec2-user'

[webservers]
172.31.83.168 ansible_ssh_user='ec2-user'
172.31.95.4 ansible_ssh_user='ec2-user'

[db]
172.31.83.155 ansible_ssh_user='ubuntu' 

[lb]
172.31.19.235 ansible_ssh_user='ubuntu'
